### ISSUE TITLE
[DOC CHANGE PROPOSAL]

### ISSUE THREAD

**Issue by busslina** [GregoryConrad/rearch-dart#32] opened 2023-12-23 21:45 UTC
https://github.com/GregoryConrad/rearch-dart/blob/b39cd673c06c932208c8d620db2eadd36c282300/packages/rearch/lib/src/side_effects.dart#L50C34-L50C34

Maybe specify that it keeps the same `getter` across rebuilds too

**Comment by GregoryConrad** [comment] 2023-12-24 00:34
That was intentional: we want `use.state` itself to return the same state setter across rebuilds so that when an == check is done on the output of a capsule, a new state setter would not cause dependents to unnecessarily rebuild (a pretty niche little optimization). The getter itself does't matter, as it will be invoked to get the value.

However, this issue made me realize a big issue with the current state getter/setters. Take this test I just wrote to confirm my thinking that fails:
```dart
  test('stateGetterSetter dependents should rebuild when state updated', () {
    (int Function(), void Function(int)) stateCapsule(CapsuleHandle use) =>
        use.stateGetterSetter(0);
    int currStateCapsule(CapsuleHandle use) => use(stateCapsule).$1();

    final container = useContainer();
    expect(container.read(currStateCapsule), equals(0));
    container.read(stateCapsule).$2(1);
    expect(container.read(currStateCapsule), equals(1)); // --------- fails here, still 0
  });
```

Because the same getter is returned, the == optimization is a little too optimistic and actually doesn't rebuild the dependent capsule! I don't know whether or not to classify this as a "bug" per se, but this is likely some unintuitive behavior. Will put a PR up to fix that issue and the code comments you referenced in a second.

**Closed** 2023-12-24 00:58 UTC

**Comment by busslina** [comment] 2023-12-24 12:27
So, for clarify myself. Do you mean that even if you call rebuild() after checking the new value is not the same the current value, it will not rebuild because you doing a equality check between former and new Side Effect return value (getter and setter) which are the same. So no updating?

**Comment by busslina** [comment] 2023-12-24 15:42
>  I don't know whether or not to classify this as a "bug".

I thing we can call it a bug because your intention is to rebuild but it wouldn't ever rebuild

**Comment by GregoryConrad** [comment] 2023-12-24 21:36
Yea. Maybe not a bug, but unintuitive behavior which is why I pushed that fix up yesterday.

rebuild() only requests for the associated capsule to be rebuilt. If that capsule’s data doesn’t change after it is rebuilt, none of the dependents/downstream capsules will be modified. Thus, we return a new getter on each build to force the new data to be different from the old data so dependents will rebuild.

**Comment by GregoryConrad** [comment] 2023-12-24 21:36
﻿
Yea. Maybe not a bug, but unintuitive behavior which is why I pushed that fix up yesterday.

rebuild() only requests for the associated capsule to be rebuilt. If that capsule’s data doesn’t change after it is rebuilt, none of the dependents/downstream capsules will be modified. Thus, we return a new getter on each build to force the new data to be different from the old data so dependents will rebuild.

**Comment by busslina** [comment] 2025-03-08 00:50
I'm reading `use.lazyData` and I have two questions:

1) Why we need to wrap the getter? I see in your comment above it's giving 0 instead of 1 on the test. But I don't understand why. And why the setter is working without the wrapper.
2) If we return from a capsule the result of `use.lazyData` seems that wrapping the getter will produce always a new object (even if the deta remains untouchedd) so it will trigger the dependants rebuild listeners. Am I correct?

**Comment by GregoryConrad** [comment] 2025-03-08 15:55
> Why we need to wrap the getter?...But I don't understand why. 

Because if we don't wrap the getter, we return the same one as we did from the first build--which is bad, since it will never change, even when the underlying data changes. So, when ReArch checks to see if the old capsule data == the new capsule data, it will always be ==, and thus no further rebuilds will occur.

> If we return from a capsule the result of use.lazyData seems that wrapping the getter will produce always a new object (even if the data remains unmodified) so it will trigger the dependants rebuild listeners. Am I correct?

If you mean a capsule that does: `capsule((use) => use.lazyData(0))`, then, yes, it will create a new object, but the capsule won't always rebuild (see the `cancelRebuild` call in the snippet you gave). Canceling rebuilds is a bit of a clunky idea, and I'd probably take it back if I could, but it's stable now. If I ever do a 2.0, removing the cancelation of rebuilds would likely be one of the changes (and I'd memoize the getter instead).

**Comment by busslina** [comment] 2025-03-08 17:51
What I really mean is that in the below example the capsule will trigger rebuilds on dependents even if the data never change (as we are generating a new object by wrapping the getter).

```dart
ValueWrapper<bool> aCapsule(CapsuleHandle use) {
  final data = use.data(false);

  final rebuild = use.rebuilder();

  use.effect(() {
    return Timer.periodic(
      const Duration(seconds: 1),
      (_) => rebuild(),
    ).cancel;
  });

  return data;
}
```

**Comment by busslina** [comment] 2025-05-10 15:12
Now it's less verbose:
```dart
use.effect(() {
      log.debug(
        msg('Tile URL: ${tileUrl.value} -- Store name: ${storeName.value}'),
      );
      return;
    }, [tileUrl, storeName]);
```

Before:
```dart
use.effect(() {
      log.debug(
        msg('Tile URL: ${tileUrl.value} -- Store name: ${storeName.value}'),
      );
      return;
    }, [tileUrl.value, storeName.value]);
```

**Comment by GregoryConrad** [comment] 2025-05-10 15:27
Ahh, that’s a nice QoL improvement I hadn’t even thought of. But yea, that’s a nice improvement
